// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDea_fApWdiNOEkcacmVHdX1VKXSAL_SKQ',
    appId: '1:534551208883:web:2f1018c7201c2b9b98e1c6',
    messagingSenderId: '534551208883',
    projectId: 'mileseducation-e4b1c',
    authDomain: 'mileseducation-e4b1c.firebaseapp.com',
    storageBucket: 'mileseducation-e4b1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0XtObEifP_GrIeZ2IbaGUQ3AnJWsYZA',
    appId: '1:534551208883:android:40bad6f70464cff198e1c6',
    messagingSenderId: '534551208883',
    projectId: 'mileseducation-e4b1c',
    storageBucket: 'mileseducation-e4b1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB34mMIjJtkKDmaXtvbuPjTPIvOEoiEUrc',
    appId: '1:534551208883:ios:d87fe3c43729d11498e1c6',
    messagingSenderId: '534551208883',
    projectId: 'mileseducation-e4b1c',
    storageBucket: 'mileseducation-e4b1c.firebasestorage.app',
    iosBundleId: 'com.example.milesEducations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB34mMIjJtkKDmaXtvbuPjTPIvOEoiEUrc',
    appId: '1:534551208883:ios:d87fe3c43729d11498e1c6',
    messagingSenderId: '534551208883',
    projectId: 'mileseducation-e4b1c',
    storageBucket: 'mileseducation-e4b1c.firebasestorage.app',
    iosBundleId: 'com.example.milesEducations',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDea_fApWdiNOEkcacmVHdX1VKXSAL_SKQ',
    appId: '1:534551208883:web:7301fb51502f3e1598e1c6',
    messagingSenderId: '534551208883',
    projectId: 'mileseducation-e4b1c',
    authDomain: 'mileseducation-e4b1c.firebaseapp.com',
    storageBucket: 'mileseducation-e4b1c.firebasestorage.app',
  );
}
